language: java
jdk: 
  - openjdk8
script:
  - ./travis.sh
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install 
#  - mvn sonar:sonar
#  - mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$GITHUB_TOKEN@github.com/hemantsonu20/cric-score-updater --tags

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: cric-ui/target/cric-ui-0.0.1-SNAPSHOT.jar
  skip_cleanup: true
  on:
    tags: false
    branch: master

notifications:
  email
    - hemantsonu20@gmail.com
addons:
  sonarqube:
    token:
      secure: $SONAR_GITHUB_TOKEN
      
before_install:
  - chmod +x ./travis.sh
